version: '3.8'

services:
  # Database Service (MySQL)
  db:
    image: mysql:8
    # environment variables for the MySQL server
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: openassets-db
      MYSQL_USER: admin
      MYSQL_PASSWORD: 1234
    # Mount the db-dump directory to initialize the database with the dump.sql
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d/
    # Expose port 3307 on the host to access the database from outside the Docker network
    ports:
      - "3307:3306"
    # Restart the container if it stops for any reason
    restart: unless-stopped

  # Backend Service
  backend:
    # Build the backend image from the Dockerfile located in the ./OpenAssets/Backend directory
    build: ./Backend
    # Map port 8080 from the container to port 8080 on the host
    ports:
      - "8080:8080"
    # Ensure the database is up and running before starting the backend
    depends_on:
      - db
    # Restart the container unless it's explicitly stopped
    restart: unless-stopped
    # Define environment variables for the Spring Boot application to connect to the database
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/openassets-db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: 1234
    volumes:
      - ./storage:/app/storage

  # Frontend Service
  frontend:
    # Build the frontend image from the Dockerfile located in the ./OpenAssets/Frontend directory
    build: ./Frontend
    # Map port 80 from the container (where Nginx serves the app) to port 80 on the host
    ports:
      - "80:80"
    # Ensure the backend is up before the frontend starts
    depends_on:
      - backend
    # Restart the container unless it's explicitly stopped
    restart: unless-stopped